Create initial donor form with submission endpoint #14
InkubatorTechnologiczny/shelter pull request #46
Opened 2023-11-15 21:33 UTC by wenta

2023-11-16 07:33 UTC, Guferos requested changes
Generally all good! It seems like you picking the Laravel skills very quickly. Thanks for the tests, finally someone done them! (I am the most quilty here for not doing them). 

There is one thing that needs to be done, the donor form should be on the animal details page rather than on it's own page. Sorry I probably should be more clearer on the task's card about this. 

See my detailed comments to see what should  be changed before merge. Thanks.

2023-11-16 07:33 UTC, Guferos commented on app/Http/Controllers/AdoptionController.php
> +            'animalName' => 'required|max:255',
Please remove `animalName` from the validation, it's not required in the post data.

2023-11-16 07:33 UTC, Guferos commented on routes/web.php
> +Route::get('/adoption/{animalId}', [AdoptionController::class, 'index'])->name('adoption');
The donor's form should be accessible from the animal details page. Therefore this route will not be needed.

2023-11-16 07:33 UTC, Guferos commented on routes/web.php
> +Route::post('/submit-donor', [AdoptionController::class, 'submitForm'])->name('submitForm');
Rather then having separate AdoptionController, it feels more logical to move the submission into the DonorController into the `store` method. Could you please move AdoptionController logic there?

2023-11-16 07:33 UTC, Guferos commented on resources/views/pages/adoptionForm.blade.php
Please move the form into the animalDetails.blade page. We should be accessing form from there (same as in Ciapkowo).

2023-11-16 07:33 UTC, Guferos commented on resources/views/pages/adoptionForm.blade.php
> +        <input type="hidden" name="animal_id" value="{{ $animalId }}">
Once moved to the animalDetails.blade file, `animal_id` will be assigned from the `$animal` object available there.

2023-11-16 07:33 UTC, Guferos commented on resources/views/pages/adoptionForm.blade.php
> +        <label for="animalName">Imię zwierzęcia:</label>
Animal name is not needed.

2023-11-16 07:33 UTC, Guferos commented on tests/Unit/AdoptionFormTest.php
Well done for the tests. Finally someone is doing them! I need to add some myself.

2023-11-16 07:33 UTC, Guferos commented on app/Http/Controllers/AdoptionController.php
As commented in other places. Please move the `submitForm` logic into the `DonorController->store` method. AdoptionController will not be needed really, we should be accessing the form from the `animalDetails.blade.php` instead.

2023-11-16 07:33 UTC, Guferos commented on resources/sass/app.scss
![Screenshot 2023-11-16 at 08 28 27](https://github.com/InkubatorTechnologiczny/shelter/assets/3239180/ba6d6513-43c4-4840-8cd5-28aea7b4ad71)

UI it's not so important at this stage, but just wanted to mention that there is something wrong with the email field (it's too short and looks different to other fields in the form). I tested on Safari 16.4

2023-11-16 22:46 UTC, Guferos commented
@wenta Please merge the dev branch before submitting fixes to the pull and run database migrations (ideally as fresh) + seeders. I just merged a significant change to the database structure that removes `animal_id` from `Donor` model and moves Animals-Donors relationship into a pivot as we need Many to many relationship rather than One to Many we had previously. This would affect your donor form submission implementation. Rather than setting `animal_id` on Donor, you would need to attach (https://laravel.com/docs/10.x/eloquent-relationships#updating-many-to-many-relationships) Animal when creating a Donor record. 

On top of that there are two more things that need to be done when creating a donor:
1) You would need to validate if submitted animal_id is correct by checking if there is Animal record with the submitted id
2) As we are going to run two queries here (save Donor and attach Animal), you need to run both queries wrapped in database transaction to ensure data integrity if one of them fails.

2023-11-18 11:24 UTC, Guferos commented
@wenta Thanks for the pr fixes. Not sure if you have seen my latest comment in this PR? Please have a look above. This branch must be merged with the `dev` first and some additional changes are required as I had to modify the way Donors are linked to Animals. It is now a many to many relationship rather than One to Many. Could you please look into that whenever possible?

2023-11-18 11:31 UTC, wenta commented
Yes I work on that ;) I will let you know when pr will be finished,  I push commits for safety.

2023-11-18 11:43 UTC, Guferos commented
@wenta Ah ok that's great, thanks. I wasn't sure if you pushed for a review or not.

2023-11-19 10:57 UTC, Guferos approved these changes
All good, thanks. We would probably need to replace the form with some sort of success message once the submission was successfull, but it wasn't part of this ticket, so I'll create a new one for that.

2023-11-19 10:57 UTC, merged